-- MySQL Script generated by MySQL Workbench
-- sáb 27 ago 2022 09:23:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema passagens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema passagens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `passagens` ;
USE `passagens` ;

-- -----------------------------------------------------
-- Table `passagens`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passagens`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(64) NOT NULL DEFAULT (SHA2(now(), 256)),
  `nome` VARCHAR(100) NOT NULL,
  `endereco` TEXT NULL DEFAULT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_data` DATETIME NULL DEFAULT NULL,
  `excluido_por` INT NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT current_timestamp,
  `data_update` DATETIME NULL DEFAULT NULL on update current_timestamp,
  PRIMARY KEY (`id`, `key`));


-- -----------------------------------------------------
-- Table `passagens`.`tipos_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passagens`.`tipos_veiculos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(64) NOT NULL DEFAULT (SHA2(now(), 256)),
  `descicao` VARCHAR(100) NOT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_data` DATETIME NULL DEFAULT NULL,
  `excluido_por` INT NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT current_timestamp,
  `data_update` DATETIME NULL DEFAULT NULL on update current_timestamp,
  PRIMARY KEY (`id`, `key`));


-- -----------------------------------------------------
-- Table `passagens`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passagens`.`veiculos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(64) NOT NULL DEFAULT (SHA2(now(), 256)),
  `tipos_veiculos_id` INT NOT NULL,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `ano` VARCHAR(45) NULL DEFAULT NULL,
  `codigo` VARCHAR(45) NULL DEFAULT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `placa` VARCHAR(45) NULL DEFAULT NULL,
  `lugares` VARCHAR(45) NULL DEFAULT NULL,
  `excluido_data` DATETIME NULL DEFAULT NULL,
  `excluido_por` INT NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT current_timestamp,
  `data_update` DATETIME NULL DEFAULT NULL on update current_timestamp,
  PRIMARY KEY (`id`, `key`),
  INDEX `fk_veiculos_tipos_veiculos_idx` (`tipos_veiculos_id` ASC) VISIBLE,
  CONSTRAINT `fk_veiculos_tipos_veiculos`
    FOREIGN KEY (`tipos_veiculos_id`)
    REFERENCES `passagens`.`tipos_veiculos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `passagens`.`viagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `passagens`.`viagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(64) NOT NULL DEFAULT (SHA2(now(), 256)),
  `descicao` VARCHAR(100) NOT NULL,
  `origem` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `data_saida` DATETIME NOT NULL,
  `data_chegada` DATETIME NOT NULL,
  `detalhes` TEXT NULL DEFAULT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_data` DATETIME NULL DEFAULT NULL,
  `excluido_por` INT NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT current_timestamp,
  `data_update` DATETIME NULL DEFAULT NULL on update current_timestamp,
  PRIMARY KEY (`id`, `key`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
