-- MySQL Script generated by MySQL Workbench
-- qui 14 jul 2022 08:06:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema automacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema automacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `automacao` DEFAULT CHARACTER SET utf8 ;
USE `automacao` ;

-- -----------------------------------------------------
-- Table `automacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  `celular` INT NULL DEFAULT NULL,
  `senha` VARCHAR(64) NULL DEFAULT NULL,
  `token` VARCHAR(64) NULL DEFAULT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_por` INT NULL DEFAULT NULL,
  `data_excluido` DATETIME NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_update` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `automacao`.`endreco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`endreco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` INT NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(15) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_por` INT NULL DEFAULT NULL,
  `data_excluido` DATETIME NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_update` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `automacao`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `endereco_id` INT NULL DEFAULT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `cpf_cnpj` INT NULL DEFAULT NULL,
  `natureza` ENUM('F', 'J') NULL DEFAULT NULL COMMENT 'F: Física; J: Jurídica',
  `documento` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Ex: RG, CNH, IE, Passaporte, Registro de classe',
  `orgao_emissor` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_por` INT NULL DEFAULT NULL,
  `data_excluido` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_pessoa_endereco_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `automacao`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `automacao`.`endreco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `automacao`.`empreendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`empreendimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endreco_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_por` INT NULL DEFAULT NULL,
  `data_excluido` DATETIME NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_update` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_empreendimento_endreco_idx` (`endreco_id` ASC) VISIBLE,
  CONSTRAINT `fk_empreendimento_endreco`
    FOREIGN KEY (`endreco_id`)
    REFERENCES `automacao`.`endreco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `automacao`.`dispositivo_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`dispositivo_tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_por` INT NULL DEFAULT NULL,
  `data_excluido` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_update` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `automacao`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`dispositivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dispositivo_tipo_id` INT NOT NULL,
  `excluido` ENUM('S', 'N') NULL DEFAULT 'N',
  `excluido_por` INT NULL DEFAULT NULL,
  `data_excluido` DATETIME NULL DEFAULT NULL,
  `data_insert` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_update` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivos_dispositivo_tipo1_idx` (`dispositivo_tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_dispositivos_dispositivo_tipo`
    FOREIGN KEY (`dispositivo_tipo_id`)
    REFERENCES `automacao`.`dispositivo_tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `automacao`.`empreendimento_dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`empreendimento_dispositivos` (
  `empreendimento_id` INT NOT NULL,
  `dispositivos_id` INT NOT NULL,
  PRIMARY KEY (`empreendimento_id`, `dispositivos_id`),
  INDEX `fk_empreendimento_has_dispositivos_dispositivos1_idx` (`dispositivos_id` ASC) VISIBLE,
  INDEX `fk_empreendimento_has_dispositivos_empreendimento1_idx` (`empreendimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_empreendimento_has_dispositivos_empreendimento1`
    FOREIGN KEY (`empreendimento_id`)
    REFERENCES `automacao`.`empreendimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empreendimento_has_dispositivos_dispositivos1`
    FOREIGN KEY (`dispositivos_id`)
    REFERENCES `automacao`.`dispositivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `automacao`.`usuario_empreendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automacao`.`usuario_empreendimento` (
  `usuario_id` INT NOT NULL,
  `empreendimento_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `empreendimento_id`),
  INDEX `fk_usuario_has_empreendimento_empreendimento1_idx` (`empreendimento_id` ASC) VISIBLE,
  INDEX `fk_usuario_has_empreendimento_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_empreendimento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `automacao`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_empreendimento_empreendimento1`
    FOREIGN KEY (`empreendimento_id`)
    REFERENCES `automacao`.`empreendimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
